"""Intake session contracts.

Covers the clinical question-answer flow: questions generated by the engine,
responses from the patient, and the full session aggregate including the
Conversation Frustration Index (CFI) for graceful human fallback.
"""

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class QuestionType(str, Enum):
    """Format of a clinical intake question."""

    OPEN_TEXT = "open_text"
    SINGLE_CHOICE = "single_choice"
    MULTI_CHOICE = "multi_choice"
    NUMERIC_SCALE = "numeric_scale"


class ClinicalDomain(str, Enum):
    """The clinical interview domain a question belongs to."""

    DEMOGRAPHICS = "demographics"
    CHIEF_COMPLAINT = "chief_complaint"
    HPI = "hpi"  # History of Presenting Illness
    SOCRATES = "socrates"  # Pain assessment dimensions
    PAST_MEDICAL = "past_medical"
    DRUG_HISTORY = "drug_history"
    ALLERGY = "allergy"
    FAMILY = "family"
    SOCIAL = "social"
    REVIEW_OF_SYSTEMS = "review_of_systems"
    DASHAVIDHA = "dashavidha"  # Ayurvedic 10-fold examination


class ResponseSource(str, Enum):
    """How the patient provided their answer."""

    VOICE = "voice"
    TOUCH = "touch"  # touchscreen button tap
    TEXT = "text"  # on-screen keyboard


class IntakeQuestion(BaseModel):
    """A clinical question generated for the patient.

    Attributes:
        question_id: Unique identifier for this question instance.
        question_text: The text shown/spoken to the patient.
        question_type: Format (open text, single choice, etc.).
        choices: Options for choice-type questions. None for open text.
        clinical_domain: Which clinical area this question covers.
    """

    model_config = ConfigDict(frozen=True)

    question_id: UUID
    question_text: str = Field(..., min_length=1)
    question_type: QuestionType
    choices: tuple[str, ...] | None = Field(
        default=None,
        description="Options for SINGLE_CHOICE or MULTI_CHOICE questions.",
    )
    clinical_domain: ClinicalDomain


class IntakeResponse(BaseModel):
    """A patient's answer to an IntakeQuestion.

    Attributes:
        question_id: References IntakeQuestion.question_id.
        response_text: Raw response text (may contain PHI — never log).
        response_source: How the response was submitted.
        extracted_data: Structured data parsed from the response.
    """

    model_config = ConfigDict(frozen=True)

    question_id: UUID
    response_text: str = Field(..., description="Raw patient response. Contains PHI — never log.")
    response_source: ResponseSource
    extracted_data: dict[str, object] = Field(
        default_factory=dict,
        description="Structured clinical data parsed from the response text.",
    )


class IntakeSession(BaseModel):
    """Aggregate state of the patient's clinical interview.

    Tracks all questions asked, responses received, and the
    Conversation Frustration Index (CFI) for graceful human fallback.

    Attributes:
        session_id: References the root SessionState.
        questions_asked: Ordered list of questions posed.
        responses: Ordered list of patient responses.
        clinical_data: Accumulated structured clinical data.
        progress: Completion fraction [0.0, 1.0].
        is_complete: True when all required domains are covered.
        triage_alerts: Red-flag alerts fired during this session.
        frustration_index: CFI — increments on communication breakdown signals.
        frustration_threshold: CFI value that triggers human fallback.
        human_fallback_triggered: True when CFI >= threshold.
    """

    model_config = ConfigDict(frozen=True)

    session_id: UUID
    questions_asked: tuple[IntakeQuestion, ...] = Field(default_factory=tuple)
    responses: tuple[IntakeResponse, ...] = Field(default_factory=tuple)
    clinical_data: dict[str, object] = Field(default_factory=dict)
    progress: float = Field(default=0.0, ge=0.0, le=1.0)
    is_complete: bool = False
    triage_alerts: tuple[object, ...] = Field(
        default_factory=tuple,
        description="TriageAlert objects — typed as object to avoid circular import.",
    )
    frustration_index: int = Field(
        default=0,
        ge=0,
        description=(
            "Conversation Frustration Index. Increments on: "
            "low ASR confidence (<0.4), repeated questions, "
            "long pauses (>10s), explicit confusion signals."
        ),
    )
    frustration_threshold: int = Field(
        default=5,
        ge=1,
        description=(
            "CFI value at which the system stops AI questioning and routes to a human desk."
        ),
    )
    human_fallback_triggered: bool = Field(
        default=False,
        description=(
            "True when frustration_index >= frustration_threshold. No further AI questions."
        ),
    )
