"""Clinical summary contracts.

Bilingual synthesized clinical summaries generated for physicians.
Each section traces back to the source medical entities that grounded it,
preventing hallucination by requiring entity-level attribution.
"""

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class SummarySection(BaseModel):
    """One section of a bilingual clinical summary.

    Attributes:
        title: Section heading (e.g. 'Chief Complaint', 'Drug History').
        content_en: Full text in English.
        content_local: Full text in the patient's local language.
        clinical_domain: Which clinical domain this section covers.
        source_entities: UUIDs of MedicalEntity objects that grounded this section.
    """

    model_config = ConfigDict(frozen=True)

    title: str = Field(..., min_length=1)
    content_en: str = Field(..., description="English language content.")
    content_local: str = Field(..., description="Content in the patient's local language.")
    clinical_domain: str = Field(..., description="Clinical domain (e.g. 'chief_complaint').")
    source_entities: tuple[UUID, ...] = Field(
        default_factory=tuple,
        description="References to MedicalEntity.entity_id that grounded this section.",
    )


class ClinicalSummary(BaseModel):
    """Bilingual clinical summary for physician review.

    Generated by the synthesis engine from the complete intake session
    and clinical timeline. Each section is entity-grounded to prevent
    LLM hallucination.

    Attributes:
        summary_id: Unique identifier for this summary.
        session_id: Session this summary was generated from.
        sections: Ordered tuple of bilingual summary sections.
    """

    model_config = ConfigDict(frozen=True)

    summary_id: UUID
    session_id: UUID
    sections: tuple[SummarySection, ...] = Field(default_factory=tuple)
