"""Triage alert contracts.

TriageAlerts are fired by the deterministic triage rule engine when
red-flag symptoms or dangerous combinations are detected in the intake.
The triage engine uses deterministic rules ONLY — no LLM involvement —
to guarantee that critical alerts are never missed due to hallucination.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class TriagePriority(str, Enum):
    """Clinical urgency level of a triage alert."""

    CRITICAL = "critical"  # immediate intervention required (e.g. FAST stroke signs)
    URGENT = "urgent"  # seen within 30 minutes (e.g. severe pain scale 8-10)
    NORMAL = "normal"  # standard queue, no immediate danger


class TriageAlert(BaseModel):
    """An emergency or urgent clinical alert fired by the triage engine.

    Triage alerts are generated by deterministic rule matching against
    patient responses. They are NOT generated by LLMs.

    Attributes:
        alert_id: Unique identifier for this alert.
        priority: Clinical urgency level.
        rule_name: Name of the rule that fired (e.g. 'FAST_STROKE_SIGNS').
        trigger_text: The patient statement that triggered the rule.
        recommended_action: Suggested immediate action for staff.
        created_at: UTC timestamp when the alert was fired.
    """

    model_config = ConfigDict(frozen=True)

    alert_id: UUID
    priority: TriagePriority
    rule_name: str = Field(..., min_length=1, description="Name of the triggered rule.")
    trigger_text: str = Field(
        ..., description="Patient statement that triggered this alert. May contain PHI."
    )
    recommended_action: str = Field(
        ..., min_length=1, description="Recommended immediate action for clinical staff."
    )
    created_at: datetime
