// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  GetQueueApiClinicianQueueGetData,
  GetQueueApiClinicianQueueGetErrors,
  GetQueueApiClinicianQueueGetResponses,
  HealthCheckApiHealthGetData,
  HealthCheckApiHealthGetResponses,
  ListDoctorsApiDoctorsGetData,
  ListDoctorsApiDoctorsGetErrors,
  ListDoctorsApiDoctorsGetResponses,
  ListPackagesApiPackagesGetData,
  ListPackagesApiPackagesGetErrors,
  ListPackagesApiPackagesGetResponses,
  PagePatientApiClinicianQueuePagePatientPostData,
  PagePatientApiClinicianQueuePagePatientPostErrors,
  PagePatientApiClinicianQueuePagePatientPostResponses,
  PurgeSessionApiSessionPurgePostData,
  PurgeSessionApiSessionPurgePostErrors,
  PurgeSessionApiSessionPurgePostResponses,
  QueueLiveStreamApiClinicianQueueLiveGetData,
  QueueLiveStreamApiClinicianQueueLiveGetErrors,
  QueueLiveStreamApiClinicianQueueLiveGetResponses,
  RespondApiIntakeRespondPostData,
  RespondApiIntakeRespondPostErrors,
  RespondApiIntakeRespondPostResponses,
  SelectDoctorApiIntakeSelectDoctorPostData,
  SelectDoctorApiIntakeSelectDoctorPostErrors,
  SelectDoctorApiIntakeSelectDoctorPostResponses,
  SelectPackageApiIntakeSelectPackagePostData,
  SelectPackageApiIntakeSelectPackagePostErrors,
  SelectPackageApiIntakeSelectPackagePostResponses,
  StartSessionApiIntakeStartPostData,
  StartSessionApiIntakeStartPostErrors,
  StartSessionApiIntakeStartPostResponses,
  VerifyPmjayApiIntakeVerifyPmjayPostData,
  VerifyPmjayApiIntakeVerifyPmjayPostErrors,
  VerifyPmjayApiIntakeVerifyPmjayPostResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Health Check
 *
 * Check system health including database connectivity.
 *
 * Performs a lightweight ``SELECT 1`` probe against the configured
 * database engine. Never raises — a DB failure is surfaced as
 * ``"database": "error"`` in the response body so load balancers can
 * still parse the JSON.
 *
 * Args:
 * engine: Async SQLAlchemy engine (injected).
 *
 * Returns:
 * dict: Health payload with keys ``status``, ``version``,
 * ``database``.
 */
export const healthCheckApiHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCheckApiHealthGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<HealthCheckApiHealthGetResponses, unknown, ThrowOnError>({
    url: '/api/health',
    ...options,
  });

/**
 * Start Session
 *
 * Start a new multi-tenant patient intake session.
 *
 * Creates a ``SessionState`` record and writes an audit event.
 * PHI is never included in the response — only the opaque ``session_id``
 * is returned to the caller.
 *
 * Args:
 * body: Session configuration supplied by the kiosk.
 * current_user: Authenticated principal (injected).
 * session_svc: Session lifecycle service (injected).
 * intake_svc: Intake processing service (injected).
 *
 * Returns:
 * StartSessionResponse: Created session metadata.
 *
 * Raises:
 * HTTPException 403: ConsentRequiredError / ConsentError.
 * HTTPException 422: Domain ValidationError.
 * HTTPException 500: Any other MediKioskError.
 */
export const startSessionApiIntakeStartPost = <ThrowOnError extends boolean = false>(
  options: Options<StartSessionApiIntakeStartPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    StartSessionApiIntakeStartPostResponses,
    StartSessionApiIntakeStartPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/intake/start',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Respond
 *
 * Process a patient response and return the next question or triage alert.
 *
 * Validates session existence and liveness via SessionService. Full
 * LLM-based question generation is deferred to Wave 6 (IntakeService).
 * A placeholder next question is returned for now.
 *
 * SECURITY: ``body.response_text`` is PHI and MUST NOT be logged.
 * Only ``session_id`` is recorded in structured logs.
 *
 * Args:
 * body: Patient response payload.
 * current_user: Authenticated principal (injected).
 * session_svc: Session lifecycle service (injected).
 * intake_svc: The actual IntakeService.
 *
 * Returns:
 * RespondResponse: Updated progress, any triage alerts, and next question.
 */
export const respondApiIntakeRespondPost = <ThrowOnError extends boolean = false>(
  options: Options<RespondApiIntakeRespondPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    RespondApiIntakeRespondPostResponses,
    RespondApiIntakeRespondPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/intake/respond',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Purge Session
 *
 * Hard-delete a session record (DPDP Right-to-Erasure).
 *
 * Permanently removes all session data from the store and writes a
 * tamper-evident audit event for compliance. This operation is
 * irreversible.
 *
 * Accepted roles: ``Kiosk_Device``, ``Triage_Nurse``.
 *
 * Args:
 * body: Purge request with session_id and reason.
 * current_user: Authenticated principal with purge permission (injected).
 * session_svc: Session lifecycle service (injected).
 *
 * Returns:
 * PurgeResponse: Confirmation that the session was purged.
 *
 * Raises:
 * HTTPException 404: SessionNotFoundError.
 * HTTPException 500: Any other MediKioskError.
 */
export const purgeSessionApiSessionPurgePost = <ThrowOnError extends boolean = false>(
  options: Options<PurgeSessionApiSessionPurgePostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PurgeSessionApiSessionPurgePostResponses,
    PurgeSessionApiSessionPurgePostErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/session/purge',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Verify Pmjay
 *
 * Verify PM-JAY eligibility and update session billing status.
 */
export const verifyPmjayApiIntakeVerifyPmjayPost = <ThrowOnError extends boolean = false>(
  options: Options<VerifyPmjayApiIntakeVerifyPmjayPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    VerifyPmjayApiIntakeVerifyPmjayPostResponses,
    VerifyPmjayApiIntakeVerifyPmjayPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/intake/verify-pmjay',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Queue
 *
 * Return the current triage queue for a department.
 */
export const getQueueApiClinicianQueueGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetQueueApiClinicianQueueGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetQueueApiClinicianQueueGetResponses,
    GetQueueApiClinicianQueueGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/clinician/queue',
    ...options,
  });

/**
 * Queue Live Stream
 *
 * Stream real-time triage queue updates via Server-Sent Events.
 */
export const queueLiveStreamApiClinicianQueueLiveGet = <ThrowOnError extends boolean = false>(
  options?: Options<QueueLiveStreamApiClinicianQueueLiveGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    QueueLiveStreamApiClinicianQueueLiveGetResponses,
    QueueLiveStreamApiClinicianQueueLiveGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/clinician/queue/live',
    ...options,
  });

/**
 * Page Patient
 *
 * Page a patient in the virtual waiting room.
 */
export const pagePatientApiClinicianQueuePagePatientPost = <ThrowOnError extends boolean = false>(
  options: Options<PagePatientApiClinicianQueuePagePatientPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PagePatientApiClinicianQueuePagePatientPostResponses,
    PagePatientApiClinicianQueuePagePatientPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/clinician/queue/page-patient',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List Doctors
 *
 * List available doctors.
 */
export const listDoctorsApiDoctorsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListDoctorsApiDoctorsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListDoctorsApiDoctorsGetResponses,
    ListDoctorsApiDoctorsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/doctors',
    ...options,
  });

/**
 * Select Doctor
 *
 * Select a doctor for a session.
 */
export const selectDoctorApiIntakeSelectDoctorPost = <ThrowOnError extends boolean = false>(
  options: Options<SelectDoctorApiIntakeSelectDoctorPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    SelectDoctorApiIntakeSelectDoctorPostResponses,
    SelectDoctorApiIntakeSelectDoctorPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/intake/select-doctor',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List Packages
 *
 * List available health packages.
 */
export const listPackagesApiPackagesGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListPackagesApiPackagesGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListPackagesApiPackagesGetResponses,
    ListPackagesApiPackagesGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/packages',
    ...options,
  });

/**
 * Select Package
 *
 * Select packages for a session.
 */
export const selectPackageApiIntakeSelectPackagePost = <ThrowOnError extends boolean = false>(
  options: Options<SelectPackageApiIntakeSelectPackagePostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    SelectPackageApiIntakeSelectPackagePostResponses,
    SelectPackageApiIntakeSelectPackagePostErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/intake/select-package',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
