// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ABDMGenerateQRResponse
 *
 * Payload returned for display as an ABDM Scan & Share QR code.
 */
export type AbdmGenerateQrResponse = {
    /**
     * Token
     *
     * Unique counter token assigned to this scan transaction
     */
    token: string;
    /**
     * Hip Id
     *
     * Health Information Provider ID (Hospital NHA ID)
     */
    hip_id?: string;
    /**
     * Hip Name
     *
     * Registered hospital facility name
     */
    hip_name?: string;
    /**
     * Counter Id
     *
     * Physical kiosk counter / terminal code
     */
    counter_id?: string;
    /**
     * Intent
     *
     * ABDM Scan and Share intent
     */
    intent?: string;
    /**
     * Qr Code Data
     *
     * Serialized JSON payload string for QR code generation
     */
    qr_code_data: string;
    /**
     * Expires At
     *
     * ISO UTC timestamp when QR code expires
     */
    expires_at: string;
    /**
     * Session Id
     *
     * Active session UUID if linked
     */
    session_id?: string | null;
};

/**
 * ABDMWebhookPayload
 *
 * Demographic profile payload sent by the ABDM Gateway / ABHA app upon scan.
 */
export type AbdmWebhookPayload = {
    /**
     * Token
     *
     * Counter / transaction token from scanned QR code
     */
    token: string;
    /**
     * Session Id
     *
     * Optional active session UUID
     */
    session_id?: string | null;
    /**
     * Name
     *
     * Patient full name from ABHA profile
     */
    name: string;
    /**
     * Age
     *
     * Patient age in years
     */
    age?: number;
    /**
     * Gender
     *
     * Patient gender (Male, Female, Other)
     */
    gender?: string;
    /**
     * Abha Id
     *
     * 14-digit ABHA number or ABHA address
     */
    abha_id: string;
    /**
     * Phone Number
     *
     * Registered mobile number
     */
    phone_number?: string | null;
    /**
     * Encrypted Payload
     *
     * Optional encrypted demographic block
     */
    encrypted_payload?: string | null;
};

/**
 * ABDMWebhookResponse
 *
 * Response returned to ABDM Gateway acknowledging profile ingestion.
 */
export type AbdmWebhookResponse = {
    /**
     * Status
     *
     * Acknowledgement status
     */
    status?: string;
    /**
     * Message
     *
     * Status message
     */
    message?: string;
    /**
     * Token
     *
     * Transaction token
     */
    token: string;
    /**
     * Session Id
     *
     * Linked session ID
     */
    session_id?: string | null;
};

/**
 * Body_transcribe_audio_api_speech_transcribe_post
 */
export type BodyTranscribeAudioApiSpeechTranscribePost = {
    /**
     * File
     *
     * Audio recording file (webm/wav)
     */
    file: Blob | File;
    /**
     * Language
     *
     * Target language code (e.g. 'hi', 'en', 'auto')
     */
    language?: string;
    /**
     * Session Id
     *
     * Optional session ID context
     */
    session_id?: string | null;
};

/**
 * Body_upload_document_api_documents_upload_post
 */
export type BodyUploadDocumentApiDocumentsUploadPost = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Document Type
     */
    document_type?: string;
};

/**
 * ClinicianOverviewResponse
 *
 * Dashboard KPIs and red flags.
 */
export type ClinicianOverviewResponse = {
    /**
     * Intakes Completed
     */
    intakes_completed: number;
    /**
     * Avg Intake Time Seconds
     */
    avg_intake_time_seconds: number;
    /**
     * Documents Processed
     */
    documents_processed: number;
    /**
     * Red Flags Caught
     */
    red_flags_caught: number;
    /**
     * Active Red Flags
     */
    active_red_flags: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * ClinicianSessionDetailResponse
 *
 * Full detail for a patient session.
 */
export type ClinicianSessionDetailResponse = {
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Token Number
     */
    token_number?: string | null;
    /**
     * Wait Time Seconds
     */
    wait_time_seconds: number;
    /**
     * Patient Profile
     */
    patient_profile?: {
        [key: string]: unknown;
    } | null;
    /**
     * Chief Complaint
     */
    chief_complaint?: string | null;
    /**
     * Triage Alerts
     */
    triage_alerts: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Timeline Events
     */
    timeline_events: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * DoctorListResponse
 *
 * API response for a list of doctors.
 */
export type DoctorListResponse = {
    /**
     * Doctors
     */
    doctors: Array<DoctorResponse>;
};

/**
 * DoctorResponse
 *
 * API response for a single doctor profile.
 */
export type DoctorResponse = {
    /**
     * Doctor Id
     */
    doctor_id: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Degrees
     */
    degrees: Array<string>;
    /**
     * Department
     */
    department: string;
    /**
     * Sub Speciality
     */
    sub_speciality?: string | null;
    /**
     * Clinical Interests
     */
    clinical_interests: Array<string>;
    /**
     * Experience Years
     */
    experience_years: number;
    /**
     * Languages
     */
    languages: Array<string>;
    /**
     * Seniority Tier
     */
    seniority_tier: string;
    /**
     * Rating
     */
    rating?: number | null;
    /**
     * Review Count
     */
    review_count: number;
    /**
     * Consultation Fee Inr
     */
    consultation_fee_inr: number;
    /**
     * Registration Fee Inr
     */
    registration_fee_inr: number;
    /**
     * Followup Free Days
     */
    followup_free_days: number;
    /**
     * Pmjay Accepted
     */
    pmjay_accepted: boolean;
    /**
     * Tpa Insurers Accepted
     */
    tpa_insurers_accepted: Array<string>;
    /**
     * Chamber Room
     */
    chamber_room?: string | null;
    /**
     * Availability Status
     */
    availability_status: string;
    /**
     * Opd Start Time
     */
    opd_start_time?: string | null;
    /**
     * Opd End Time
     */
    opd_end_time?: string | null;
};

/**
 * DocumentScan
 *
 * A scanned physical medical document.
 *
 * Attributes:
 * scan_id: Unique identifier for this scan.
 * session_id: Session this document belongs to.
 * document_type: Category of the document.
 * image_ref: Storage key/path to the image file.
 * extracted_text: Full text extracted by the OCR pipeline (may contain PHI).
 * confidence: OCR extraction confidence score [0.0, 1.0].
 */
export type DocumentScan = {
    /**
     * Scan Id
     */
    scan_id: string;
    /**
     * Session Id
     */
    session_id: string;
    document_type: DocumentType;
    /**
     * Image Ref
     *
     * Storage reference to the image file.
     */
    image_ref: string;
    /**
     * Extracted Text
     *
     * OCR-extracted text. May contain PHI — never log.
     */
    extracted_text: string;
    /**
     * Confidence
     *
     * OCR confidence [0.0, 1.0].
     */
    confidence: number;
};

/**
 * DocumentType
 *
 * Category of scanned medical document.
 */
export type DocumentType = 'prescription' | 'lab_report' | 'discharge_summary' | 'referral' | 'other';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * PMJAYVerificationResult
 *
 * Result of a PM-JAY eligibility verification check.
 */
export type PmjayVerificationResult = {
    /**
     * Eligible
     */
    eligible: boolean;
    /**
     * Pmjay Id
     */
    pmjay_id?: string | null;
    /**
     * Beneficiary Name
     */
    beneficiary_name?: string | null;
    /**
     * State Code
     */
    state_code?: string | null;
    /**
     * Coverage Amount Inr
     */
    coverage_amount_inr: number;
    /**
     * Verified At
     */
    verified_at: string;
    /**
     * Message
     */
    message: string;
};

/**
 * PackageListResponse
 *
 * API response for a list of packages.
 */
export type PackageListResponse = {
    /**
     * Packages
     */
    packages: Array<PackageResponse>;
};

/**
 * PackageResponse
 *
 * API response for a single hospital package.
 */
export type PackageResponse = {
    /**
     * Package Id
     */
    package_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Category
     */
    category: string;
    /**
     * Description
     */
    description: string;
    /**
     * Inclusions
     */
    inclusions: Array<string>;
    /**
     * Lab Tests
     */
    lab_tests: Array<string>;
    /**
     * Price Inr
     */
    price_inr: number;
    /**
     * Discounted Price Inr
     */
    discounted_price_inr?: number | null;
    /**
     * Pmjay Covered
     */
    pmjay_covered: boolean;
    /**
     * Department
     */
    department: string;
    /**
     * Turnaround Hours
     */
    turnaround_hours: number;
};

/**
 * PagePatientRequest
 *
 * Request to page a patient in the virtual waiting room.
 */
export type PagePatientRequest = {
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Phone Number
     */
    phone_number: string;
    /**
     * Turns Ahead
     */
    turns_ahead: number;
};

/**
 * PagePatientResponse
 *
 * Response for paging a patient.
 */
export type PagePatientResponse = {
    /**
     * Paged
     */
    paged: boolean;
    /**
     * Token
     */
    token: string;
    /**
     * Turns Ahead
     */
    turns_ahead: number;
};

/**
 * PurgeRequest
 *
 * Request body for POST /api/session/purge (DPDP hard purge).
 *
 * Attributes:
 * session_id: Session to hard-delete.
 * reason: Why the purge is being triggered.
 */
export type PurgeRequest = {
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Reason
     *
     * Purge reason: walk_away|user_request
     */
    reason?: string;
};

/**
 * PurgeResponse
 *
 * Response body for POST /api/session/purge.
 *
 * Attributes:
 * session_id: Session that was purged.
 * purged: True when the purge succeeded.
 * message: Human-readable confirmation (PHI-free).
 */
export type PurgeResponse = {
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Purged
     */
    purged: boolean;
    /**
     * Message
     */
    message: string;
};

/**
 * QueueEntry
 *
 * A single entry in the clinician triage queue.
 *
 * Attributes:
 * session_id: Opaque session reference (no PHI).
 * department_id: Clinical department this entry belongs to.
 * triage_priority: Urgency level: critical|urgent|normal.
 * wait_time_seconds: How long the patient has been waiting.
 * status: Current lifecycle status of the session.
 */
export type QueueEntry = {
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Department Id
     */
    department_id: string;
    /**
     * Triage Priority
     *
     * critical|urgent|normal
     */
    triage_priority: string;
    /**
     * Wait Time Seconds
     */
    wait_time_seconds: number;
    /**
     * Status
     */
    status: string;
};

/**
 * QueueResponse
 *
 * Response body for GET /api/clinician/queue.
 *
 * Attributes:
 * department_id: The department whose queue is returned.
 * entries: Ordered list of queue entries (highest priority first).
 * total_count: Total number of active sessions in the queue.
 */
export type QueueResponse = {
    /**
     * Department Id
     */
    department_id: string;
    /**
     * Entries
     */
    entries: Array<QueueEntry>;
    /**
     * Total Count
     */
    total_count: number;
};

/**
 * RespondRequest
 *
 * Request body for POST /api/intake/respond.
 *
 * Attributes:
 * session_id: Existing session to continue.
 * response_text: Patient's answer text. Contains PHI — never log.
 * confidence: ASR or input confidence score [0.0, 1.0].
 */
export type RespondRequest = {
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Response Text
     *
     * Patient response. PHI — never log.
     */
    response_text: string;
    /**
     * Confidence
     *
     * Input confidence score
     */
    confidence?: number;
};

/**
 * RespondResponse
 *
 * Response body for POST /api/intake/respond.
 *
 * Attributes:
 * session_id: Session that was updated.
 * intake_progress: Updated completion fraction [0.0, 1.0].
 * human_fallback_triggered: True when CFI has breached its threshold.
 * triage_alerts: List of red-flag alert summaries (PHI-free).
 * next_question: Next question text to display/speak, or None if complete.
 */
export type RespondResponse = {
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Intake Progress
     */
    intake_progress: number;
    /**
     * Human Fallback Triggered
     */
    human_fallback_triggered: boolean;
    /**
     * Triage Alerts
     */
    triage_alerts: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Next Question
     */
    next_question: string | null;
};

/**
 * SelectDoctorRequest
 *
 * Request to select a doctor for a session.
 */
export type SelectDoctorRequest = {
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Doctor Id
     */
    doctor_id: string;
};

/**
 * SelectDoctorResponse
 *
 * Response after selecting a doctor.
 */
export type SelectDoctorResponse = {
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Doctor Id
     */
    doctor_id: string;
    /**
     * Message
     */
    message: string;
};

/**
 * SelectPackageRequest
 *
 * Request to select packages for a session.
 */
export type SelectPackageRequest = {
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Package Ids
     */
    package_ids: Array<string>;
};

/**
 * SelectPackageResponse
 *
 * Response after selecting packages.
 */
export type SelectPackageResponse = {
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Package Ids
     */
    package_ids: Array<string>;
    /**
     * Message
     */
    message: string;
};

/**
 * StartSessionRequest
 *
 * Request body for POST /api/intake/start.
 *
 * Attributes:
 * patient_language: BCP-47 language code for the session.
 * tenant_id: Multi-tenant identifier for the hospital/facility.
 * department_id: Target clinical department.
 * informant_type: Who is physically answering (patient|relative|caregiver).
 */
export type StartSessionRequest = {
    /**
     * Patient Language
     *
     * BCP-47 language code
     */
    patient_language?: string;
    /**
     * Tenant Id
     *
     * Multi-tenant facility identifier
     */
    tenant_id?: string;
    /**
     * Department Id
     *
     * Target clinical department
     */
    department_id?: string;
    /**
     * Informant Type
     *
     * Who is answering: patient|relative|caregiver
     */
    informant_type?: string;
};

/**
 * StartSessionResponse
 *
 * Response body for POST /api/intake/start.
 *
 * Attributes:
 * session_id: Unique identifier for the created session.
 * status: Current session lifecycle status string.
 * intake_progress: Completion fraction [0.0, 1.0].
 * message: Human-readable status message (PHI-free).
 */
export type StartSessionResponse = {
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Intake Progress
     */
    intake_progress: number;
    /**
     * Message
     */
    message: string;
};

/**
 * TokenRequest
 */
export type TokenRequest = {
    /**
     * Client Id
     *
     * Client identifier
     */
    client_id: string;
    /**
     * Role
     *
     * Role to assume
     */
    role?: string;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
    /**
     * Expires In
     */
    expires_in: number;
};

/**
 * TranscribeResponse
 *
 * Transcription response payload.
 */
export type TranscribeResponse = {
    /**
     * Text
     *
     * Transcribed speech text
     */
    text: string;
    /**
     * Language
     *
     * Detected or processed language code
     */
    language?: string;
    /**
     * Confidence
     *
     * Transcription confidence score between 0.0 and 1.0
     */
    confidence?: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VerifyPMJAYRequest
 *
 * Request to verify PM-JAY eligibility.
 */
export type VerifyPmjayRequest = {
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Pmjay Id
     *
     * Optional PM-JAY Beneficiary ID
     */
    pmjay_id?: string | null;
    /**
     * Abha Number
     *
     * Optional ABHA Number
     */
    abha_number?: string | null;
};

export type HealthCheckApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthCheckApiHealthGetResponses = {
    /**
     * Response Health Check Api Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthCheckApiHealthGetResponse = HealthCheckApiHealthGetResponses[keyof HealthCheckApiHealthGetResponses];

export type StartSessionApiIntakeStartPostData = {
    body: StartSessionRequest;
    path?: never;
    query?: {
        /**
         * Token
         *
         * JWT token for SSE/WebSocket clients
         */
        token?: string | null;
    };
    url: '/api/intake/start';
};

export type StartSessionApiIntakeStartPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartSessionApiIntakeStartPostError = StartSessionApiIntakeStartPostErrors[keyof StartSessionApiIntakeStartPostErrors];

export type StartSessionApiIntakeStartPostResponses = {
    /**
     * Successful Response
     */
    201: StartSessionResponse;
};

export type StartSessionApiIntakeStartPostResponse = StartSessionApiIntakeStartPostResponses[keyof StartSessionApiIntakeStartPostResponses];

export type RespondApiIntakeRespondPostData = {
    body: RespondRequest;
    path?: never;
    query?: {
        /**
         * Token
         *
         * JWT token for SSE/WebSocket clients
         */
        token?: string | null;
    };
    url: '/api/intake/respond';
};

export type RespondApiIntakeRespondPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RespondApiIntakeRespondPostError = RespondApiIntakeRespondPostErrors[keyof RespondApiIntakeRespondPostErrors];

export type RespondApiIntakeRespondPostResponses = {
    /**
     * Successful Response
     */
    200: RespondResponse;
};

export type RespondApiIntakeRespondPostResponse = RespondApiIntakeRespondPostResponses[keyof RespondApiIntakeRespondPostResponses];

export type PurgeSessionApiSessionPurgePostData = {
    body: PurgeRequest;
    path?: never;
    query?: {
        /**
         * Token
         *
         * JWT token for SSE/WebSocket clients
         */
        token?: string | null;
    };
    url: '/api/session/purge';
};

export type PurgeSessionApiSessionPurgePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PurgeSessionApiSessionPurgePostError = PurgeSessionApiSessionPurgePostErrors[keyof PurgeSessionApiSessionPurgePostErrors];

export type PurgeSessionApiSessionPurgePostResponses = {
    /**
     * Successful Response
     */
    200: PurgeResponse;
};

export type PurgeSessionApiSessionPurgePostResponse = PurgeSessionApiSessionPurgePostResponses[keyof PurgeSessionApiSessionPurgePostResponses];

export type VerifyPmjayApiIntakeVerifyPmjayPostData = {
    body: VerifyPmjayRequest;
    path?: never;
    query?: {
        /**
         * Token
         *
         * JWT token for SSE/WebSocket clients
         */
        token?: string | null;
    };
    url: '/api/intake/verify-pmjay';
};

export type VerifyPmjayApiIntakeVerifyPmjayPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyPmjayApiIntakeVerifyPmjayPostError = VerifyPmjayApiIntakeVerifyPmjayPostErrors[keyof VerifyPmjayApiIntakeVerifyPmjayPostErrors];

export type VerifyPmjayApiIntakeVerifyPmjayPostResponses = {
    /**
     * Successful Response
     */
    200: PmjayVerificationResult;
};

export type VerifyPmjayApiIntakeVerifyPmjayPostResponse = VerifyPmjayApiIntakeVerifyPmjayPostResponses[keyof VerifyPmjayApiIntakeVerifyPmjayPostResponses];

export type GetQueueApiClinicianQueueGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Department Id
         *
         * Department to query
         */
        department_id?: string;
        /**
         * Token
         *
         * JWT token for SSE/WebSocket clients
         */
        token?: string | null;
    };
    url: '/api/clinician/queue';
};

export type GetQueueApiClinicianQueueGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQueueApiClinicianQueueGetError = GetQueueApiClinicianQueueGetErrors[keyof GetQueueApiClinicianQueueGetErrors];

export type GetQueueApiClinicianQueueGetResponses = {
    /**
     * Successful Response
     */
    200: QueueResponse;
};

export type GetQueueApiClinicianQueueGetResponse = GetQueueApiClinicianQueueGetResponses[keyof GetQueueApiClinicianQueueGetResponses];

export type QueueLiveStreamApiClinicianQueueLiveGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Department Id
         *
         * Department to stream
         */
        department_id?: string;
        /**
         * Token
         *
         * JWT token for SSE/WebSocket clients
         */
        token?: string | null;
    };
    url: '/api/clinician/queue/live';
};

export type QueueLiveStreamApiClinicianQueueLiveGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type QueueLiveStreamApiClinicianQueueLiveGetError = QueueLiveStreamApiClinicianQueueLiveGetErrors[keyof QueueLiveStreamApiClinicianQueueLiveGetErrors];

export type QueueLiveStreamApiClinicianQueueLiveGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PagePatientApiClinicianQueuePagePatientPostData = {
    body: PagePatientRequest;
    path?: never;
    query?: {
        /**
         * Token
         *
         * JWT token for SSE/WebSocket clients
         */
        token?: string | null;
    };
    url: '/api/clinician/queue/page-patient';
};

export type PagePatientApiClinicianQueuePagePatientPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PagePatientApiClinicianQueuePagePatientPostError = PagePatientApiClinicianQueuePagePatientPostErrors[keyof PagePatientApiClinicianQueuePagePatientPostErrors];

export type PagePatientApiClinicianQueuePagePatientPostResponses = {
    /**
     * Successful Response
     */
    200: PagePatientResponse;
};

export type PagePatientApiClinicianQueuePagePatientPostResponse = PagePatientApiClinicianQueuePagePatientPostResponses[keyof PagePatientApiClinicianQueuePagePatientPostResponses];

export type GetOverviewApiClinicianOverviewGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Token
         *
         * JWT token for SSE/WebSocket clients
         */
        token?: string | null;
    };
    url: '/api/clinician/overview';
};

export type GetOverviewApiClinicianOverviewGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOverviewApiClinicianOverviewGetError = GetOverviewApiClinicianOverviewGetErrors[keyof GetOverviewApiClinicianOverviewGetErrors];

export type GetOverviewApiClinicianOverviewGetResponses = {
    /**
     * Successful Response
     */
    200: ClinicianOverviewResponse;
};

export type GetOverviewApiClinicianOverviewGetResponse = GetOverviewApiClinicianOverviewGetResponses[keyof GetOverviewApiClinicianOverviewGetResponses];

export type GetSessionDetailApiClinicianSessionSessionIdGetData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: {
        /**
         * Token
         *
         * JWT token for SSE/WebSocket clients
         */
        token?: string | null;
    };
    url: '/api/clinician/session/{session_id}';
};

export type GetSessionDetailApiClinicianSessionSessionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSessionDetailApiClinicianSessionSessionIdGetError = GetSessionDetailApiClinicianSessionSessionIdGetErrors[keyof GetSessionDetailApiClinicianSessionSessionIdGetErrors];

export type GetSessionDetailApiClinicianSessionSessionIdGetResponses = {
    /**
     * Successful Response
     */
    200: ClinicianSessionDetailResponse;
};

export type GetSessionDetailApiClinicianSessionSessionIdGetResponse = GetSessionDetailApiClinicianSessionSessionIdGetResponses[keyof GetSessionDetailApiClinicianSessionSessionIdGetResponses];

export type ListDoctorsApiDoctorsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Department
         *
         * Filter by department
         */
        department?: string | null;
        /**
         * Language
         *
         * Filter by language code
         */
        language?: string | null;
        /**
         * Token
         *
         * JWT token for SSE/WebSocket clients
         */
        token?: string | null;
    };
    url: '/api/doctors';
};

export type ListDoctorsApiDoctorsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDoctorsApiDoctorsGetError = ListDoctorsApiDoctorsGetErrors[keyof ListDoctorsApiDoctorsGetErrors];

export type ListDoctorsApiDoctorsGetResponses = {
    /**
     * Successful Response
     */
    200: DoctorListResponse;
};

export type ListDoctorsApiDoctorsGetResponse = ListDoctorsApiDoctorsGetResponses[keyof ListDoctorsApiDoctorsGetResponses];

export type SelectDoctorApiIntakeSelectDoctorPostData = {
    body: SelectDoctorRequest;
    path?: never;
    query?: {
        /**
         * Token
         *
         * JWT token for SSE/WebSocket clients
         */
        token?: string | null;
    };
    url: '/api/intake/select-doctor';
};

export type SelectDoctorApiIntakeSelectDoctorPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SelectDoctorApiIntakeSelectDoctorPostError = SelectDoctorApiIntakeSelectDoctorPostErrors[keyof SelectDoctorApiIntakeSelectDoctorPostErrors];

export type SelectDoctorApiIntakeSelectDoctorPostResponses = {
    /**
     * Successful Response
     */
    200: SelectDoctorResponse;
};

export type SelectDoctorApiIntakeSelectDoctorPostResponse = SelectDoctorApiIntakeSelectDoctorPostResponses[keyof SelectDoctorApiIntakeSelectDoctorPostResponses];

export type ListPackagesApiPackagesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Department
         *
         * Filter by department
         */
        department?: string | null;
        /**
         * Category
         *
         * Filter by category
         */
        category?: string | null;
        /**
         * Token
         *
         * JWT token for SSE/WebSocket clients
         */
        token?: string | null;
    };
    url: '/api/packages';
};

export type ListPackagesApiPackagesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPackagesApiPackagesGetError = ListPackagesApiPackagesGetErrors[keyof ListPackagesApiPackagesGetErrors];

export type ListPackagesApiPackagesGetResponses = {
    /**
     * Successful Response
     */
    200: PackageListResponse;
};

export type ListPackagesApiPackagesGetResponse = ListPackagesApiPackagesGetResponses[keyof ListPackagesApiPackagesGetResponses];

export type SelectPackageApiIntakeSelectPackagePostData = {
    body: SelectPackageRequest;
    path?: never;
    query?: {
        /**
         * Token
         *
         * JWT token for SSE/WebSocket clients
         */
        token?: string | null;
    };
    url: '/api/intake/select-package';
};

export type SelectPackageApiIntakeSelectPackagePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SelectPackageApiIntakeSelectPackagePostError = SelectPackageApiIntakeSelectPackagePostErrors[keyof SelectPackageApiIntakeSelectPackagePostErrors];

export type SelectPackageApiIntakeSelectPackagePostResponses = {
    /**
     * Successful Response
     */
    200: SelectPackageResponse;
};

export type SelectPackageApiIntakeSelectPackagePostResponse = SelectPackageApiIntakeSelectPackagePostResponses[keyof SelectPackageApiIntakeSelectPackagePostResponses];

export type GenerateTokenApiAuthTokenPostData = {
    body: TokenRequest;
    path?: never;
    query?: never;
    url: '/api/auth/token';
};

export type GenerateTokenApiAuthTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateTokenApiAuthTokenPostError = GenerateTokenApiAuthTokenPostErrors[keyof GenerateTokenApiAuthTokenPostErrors];

export type GenerateTokenApiAuthTokenPostResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type GenerateTokenApiAuthTokenPostResponse = GenerateTokenApiAuthTokenPostResponses[keyof GenerateTokenApiAuthTokenPostResponses];

export type UploadDocumentApiDocumentsUploadPostData = {
    body: BodyUploadDocumentApiDocumentsUploadPost;
    path?: never;
    query?: {
        /**
         * Token
         *
         * JWT token for SSE/WebSocket clients
         */
        token?: string | null;
    };
    url: '/api/documents/upload';
};

export type UploadDocumentApiDocumentsUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadDocumentApiDocumentsUploadPostError = UploadDocumentApiDocumentsUploadPostErrors[keyof UploadDocumentApiDocumentsUploadPostErrors];

export type UploadDocumentApiDocumentsUploadPostResponses = {
    /**
     * Successful Response
     */
    200: DocumentScan;
};

export type UploadDocumentApiDocumentsUploadPostResponse = UploadDocumentApiDocumentsUploadPostResponses[keyof UploadDocumentApiDocumentsUploadPostResponses];

export type ListSessionDocumentsApiDocumentsSessionSessionIdGetData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: {
        /**
         * Token
         *
         * JWT token for SSE/WebSocket clients
         */
        token?: string | null;
    };
    url: '/api/documents/session/{session_id}';
};

export type ListSessionDocumentsApiDocumentsSessionSessionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSessionDocumentsApiDocumentsSessionSessionIdGetError = ListSessionDocumentsApiDocumentsSessionSessionIdGetErrors[keyof ListSessionDocumentsApiDocumentsSessionSessionIdGetErrors];

export type ListSessionDocumentsApiDocumentsSessionSessionIdGetResponses = {
    /**
     * Response List Session Documents Api Documents Session  Session Id  Get
     *
     * Successful Response
     */
    200: Array<DocumentScan>;
};

export type ListSessionDocumentsApiDocumentsSessionSessionIdGetResponse = ListSessionDocumentsApiDocumentsSessionSessionIdGetResponses[keyof ListSessionDocumentsApiDocumentsSessionSessionIdGetResponses];

export type TranscribeAudioApiSpeechTranscribePostData = {
    body: BodyTranscribeAudioApiSpeechTranscribePost;
    path?: never;
    query?: never;
    url: '/api/speech/transcribe';
};

export type TranscribeAudioApiSpeechTranscribePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TranscribeAudioApiSpeechTranscribePostError = TranscribeAudioApiSpeechTranscribePostErrors[keyof TranscribeAudioApiSpeechTranscribePostErrors];

export type TranscribeAudioApiSpeechTranscribePostResponses = {
    /**
     * Successful Response
     */
    200: TranscribeResponse;
};

export type TranscribeAudioApiSpeechTranscribePostResponse = TranscribeAudioApiSpeechTranscribePostResponses[keyof TranscribeAudioApiSpeechTranscribePostResponses];

export type GenerateAbdmQrApiAbdmGenerateQrGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Session Id
         *
         * Active intake session identifier
         */
        session_id?: string | null;
        /**
         * Kiosk Id
         *
         * Physical kiosk identifier
         */
        kiosk_id?: string;
    };
    url: '/api/abdm/generate-qr';
};

export type GenerateAbdmQrApiAbdmGenerateQrGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateAbdmQrApiAbdmGenerateQrGetError = GenerateAbdmQrApiAbdmGenerateQrGetErrors[keyof GenerateAbdmQrApiAbdmGenerateQrGetErrors];

export type GenerateAbdmQrApiAbdmGenerateQrGetResponses = {
    /**
     * Successful Response
     */
    200: AbdmGenerateQrResponse;
};

export type GenerateAbdmQrApiAbdmGenerateQrGetResponse = GenerateAbdmQrApiAbdmGenerateQrGetResponses[keyof GenerateAbdmQrApiAbdmGenerateQrGetResponses];

export type AbdmEventsBySessionApiAbdmEventsSessionIdGetData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: {
        /**
         * Token
         *
         * Optional counter token to also subscribe to
         */
        token?: string | null;
        /**
         * Max Events
         *
         * Optional limit on events before stream close
         */
        max_events?: number | null;
    };
    url: '/api/abdm/events/{session_id}';
};

export type AbdmEventsBySessionApiAbdmEventsSessionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AbdmEventsBySessionApiAbdmEventsSessionIdGetError = AbdmEventsBySessionApiAbdmEventsSessionIdGetErrors[keyof AbdmEventsBySessionApiAbdmEventsSessionIdGetErrors];

export type AbdmEventsBySessionApiAbdmEventsSessionIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AbdmEventsQueryApiAbdmEventsGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Session Id
         *
         * Active session ID to stream
         */
        session_id: string;
        /**
         * Token
         *
         * Optional counter token
         */
        token?: string | null;
        /**
         * Max Events
         *
         * Optional limit on events before stream close
         */
        max_events?: number | null;
    };
    url: '/api/abdm/events';
};

export type AbdmEventsQueryApiAbdmEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AbdmEventsQueryApiAbdmEventsGetError = AbdmEventsQueryApiAbdmEventsGetErrors[keyof AbdmEventsQueryApiAbdmEventsGetErrors];

export type AbdmEventsQueryApiAbdmEventsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AbdmWebhookApiAbdmWebhookPostData = {
    body: AbdmWebhookPayload;
    path?: never;
    query?: never;
    url: '/api/abdm/webhook';
};

export type AbdmWebhookApiAbdmWebhookPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AbdmWebhookApiAbdmWebhookPostError = AbdmWebhookApiAbdmWebhookPostErrors[keyof AbdmWebhookApiAbdmWebhookPostErrors];

export type AbdmWebhookApiAbdmWebhookPostResponses = {
    /**
     * Successful Response
     */
    200: AbdmWebhookResponse;
};

export type AbdmWebhookApiAbdmWebhookPostResponse = AbdmWebhookApiAbdmWebhookPostResponses[keyof AbdmWebhookApiAbdmWebhookPostResponses];
